name: assignment
description: My first flutter assignment at Niveus.

publish_to: 'none'

version: 1.2.4+15

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts:
  sizer:
  flutter_bloc:
  equatable:
  lottie:
  shared_preferences:
  text_to_speech:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/re/
    - assets/rc/
    - assets/mt/
    - assets/dio/